[package]
name = "purecv"
version = "0.1.0"
authors = ["Walter Perdan <https://github.com/kalwalt>"]
edition = "2021"
description = "A pure Rust, high-performance computer vision library focused on safety and portability."
license = "MIT OR Apache-2.0"
repository = "https://github.com/kalwalt/purecv"
readme = "README.md"
keywords = ["computer-vision", "image-processing", "opencv", "wasm", "simd"]
categories = ["computer-vision", "science", "wasm"]

[dependencies]
# Parallelism: Essential for matching C++ performance
rayon = { version="1.10", optional = true}


# Math & Linear Algebra: Provide the underlying structure for Mat/Matrix
# We use this as a dependency if you want to leverage existing BLAS/SIMD optimizations
# or you can stick to your custom Matrix implementation.
num-traits = "0.2"


# Logging/Tracing for debugging algorithms
log = "0.4"

[dev-dependencies]
image = "0.25"
# Benchmark tools: Crucial for comparing performance with OpenCV C++
criterion = "0.5"

[features]
default = ["std", "parallel"]
std = []
parallel = ["rayon"]

# Feature for WASM specific optimizations
wasm = []

[[bench]]
name = "arithm_bench"
harness = false

[[bench]]
name = "imgproc_bench"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort" # Smaller binary size and better for WASM/System safety