[workspace]
members = ["crates/wasm"]
[workspace.package]
name = "purecv"
version = "0.1.4"
authors = ["Walter Perdan <https://github.com/kalwalt>"]
edition = "2021"
description = "A pure Rust, high-performance computer vision library focused on safety and portability."
license = "LGPL-2.1-or-later"
repository = "https://github.com/webarkit/purecv"
readme = "README.md"
keywords = ["computer-vision", "image-processing", "opencv", "wasm", "simd"]
categories = ["computer-vision", "science", "wasm"]

