#!/usr/bin/env node
// Regenerates src/features2d/orb_opencv_ref.rs: OpenCV 4.10.0 (opencv.js)
// reference descriptors for purecv's ORB (purecv#124).
//
//   node scripts/opencv_ref/gen_orb_descriptors.js [out.rs]
//
// opencv.js is located via $OPENCV_JS, defaulting to a sibling checkout:
//   <repo>/../opencv-em/opencv_js/bin/opencv.js
// The image is built from integer arithmetic only, so its Rust twin
// (orb_ref_image() in src/features2d/tests.rs) is byte-identical; the FNV-1a
// checksum written into the fixture pins that.
'use strict';
const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const OPENCV_JS = process.env.OPENCV_JS
  || path.resolve(REPO_ROOT, '..', 'opencv-em', 'opencv_js', 'bin', 'opencv.js');
const OUT_RS = process.argv[2] || path.join(REPO_ROOT, 'src', 'features2d', 'orb_opencv_ref.rs');
const HEADER_TXT = path.join(REPO_ROOT, '.agents', 'skills', 'license-header-adder', 'resources', 'HEADER.txt');

const W = 192;
const H = 192;
const N_KP = 40;
const ANGLES = [0, 17.5, 90, 133.3, 270.9, 45, 180, 359.5, 222.2, 300.1,
                11.25, 60, 120, 243.7, 315, 5.5, 72.8, 199.9, 30, 150];

// ---- deterministic integer-only image; keep in sync with orb_ref_image() ----
function hash32(x) { // "lowbias32"
  x = x >>> 0;
  x = (x ^ (x >>> 16)) >>> 0; x = Math.imul(x, 0x7feb352d) >>> 0;
  x = (x ^ (x >>> 15)) >>> 0; x = Math.imul(x, 0x846ca68b) >>> 0;
  return (x ^ (x >>> 16)) >>> 0;
}
function pixel(x, y) {
  const coarse = hash32((((y >>> 3) * 64 + (x >>> 3)) ^ 0x9e3779b9) >>> 0) & 0xff; // 8x8 cells
  const fine = hash32(((y * W + x) ^ 0x85ebca6b) >>> 0) & 0x3f;
  let v = ((coarse * 3) >>> 2) + fine; // 0..=254
  if (x >= 20 && x < 84 && y >= 28 && y < 92) v = 255 - v;
  if (x >= 100 && x < 172 && y >= 56 && y < 124) v = (v >>> 1) + 96;
  if (x >= 48 && x < 144 && y >= 132 && y < 176) v ^= 0x5a;
  return v & 0xff;
}
function fnv1a32(bytes) {
  let h = 0x811c9dc5;
  for (let i = 0; i < bytes.length; i++) h = Math.imul(h ^ bytes[i], 0x01000193) >>> 0;
  return h >>> 0;
}
function makeKeypoints() {
  const kps = [];
  for (let i = 0; i < N_KP; i++) {
    kps.push({
      x: 40 + ((i * 37 + 11) % 112), // 40..=151: >= 40 px from every border
      y: 40 + ((i * 59 + 23) % 112),
      angle: Math.fround(ANGLES[i % ANGLES.length]),
    });
  }
  return kps;
}
const f32bits = (v) => { const d = new DataView(new ArrayBuffer(4)); d.setFloat32(0, v); return d.getUint32(0); };
const hex32 = (v) => '0x' + (v >>> 0).toString(16).padStart(8, '0');
const hex8 = (v) => '0x' + v.toString(16).padStart(2, '0');

async function loadCv() {
  if (!fs.existsSync(OPENCV_JS)) {
    throw new Error(`opencv.js not found at ${OPENCV_JS}; set OPENCV_JS=/path/to/opencv.js`);
  }
  let cv = require(OPENCV_JS);
  if (typeof cv === 'function') cv = cv();
  if (cv && typeof cv.then === 'function') cv = await cv;
  if (!cv.Mat) await new Promise((resolve) => { cv.onRuntimeInitialized = resolve; });
  return cv;
}

(async () => {
  const cv = await loadCv();
  const version = (cv.getBuildInformation().match(/Version control:\s*(\S+)/) || [])[1] || 'unknown';

  const px = new Uint8Array(W * H);
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) px[y * W + x] = pixel(x, y);
  const img = cv.matFromArray(H, W, cv.CV_8UC1, Array.from(px));

  const kps = makeKeypoints();
  const kpv = new cv.KeyPointVector();
  for (const k of kps) {
    kpv.push_back({ pt: { x: k.x, y: k.y }, size: 31, angle: k.angle, response: 0, octave: 0, class_id: -1 });
  }
  // cv.ORB defaults: 500, 1.2, 8 levels, edgeThreshold 31, firstLevel 0,
  // WTA_K 2, HARRIS_SCORE, patchSize 31, fastThreshold 20.
  const orb = new cv.ORB(500);
  const desc = new cv.Mat();
  orb.compute(img, kpv, desc);

  // OpenCV must keep every keypoint, in order, with its angle untouched.
  if (kpv.size() !== kps.length || desc.rows !== kps.length || desc.cols !== 32) {
    throw new Error(`OpenCV changed the keypoint set: ${kpv.size()} kps, desc ${desc.rows}x${desc.cols}`);
  }
  for (let i = 0; i < kps.length; i++) {
    const k = kpv.get(i);
    if (k.pt.x !== kps[i].x || k.pt.y !== kps[i].y || f32bits(k.angle) !== f32bits(kps[i].angle) || k.octave !== 0) {
      throw new Error(`OpenCV modified keypoint ${i}`);
    }
  }

  const header = fs.readFileSync(HEADER_TXT, 'utf8').replace('{{FILENAME}}', path.basename(OUT_RS)).trimEnd();
  const out = [header, '',
    '// @generated by scripts/opencv_ref/gen_orb_descriptors.js -- DO NOT EDIT.',
    `// Reference: OpenCV ${version} (opencv.js), cv.ORB defaults, orb.compute() on the`,
    '// integer-generated image orb_ref_image() with the keypoints below.', '',
    `pub(crate) const ORB_REF_WIDTH: usize = ${W};`,
    `pub(crate) const ORB_REF_HEIGHT: usize = ${H};`, '',
    '/// FNV-1a 32 of the generated image pixels (row-major).',
    `pub(crate) const ORB_REF_IMAGE_FNV1A: u32 = ${hex32(fnv1a32(px))};`, '',
    '/// Level-0 keypoints as (x, y, angle f32 bits); size 31, octave 0.',
    '#[rustfmt::skip]',
    `pub(crate) const ORB_REF_KEYPOINTS: [(f32, f32, u32); ${kps.length}] = [`];
  for (const k of kps) out.push(`    (${k.x.toFixed(1)}, ${k.y.toFixed(1)}, ${hex32(f32bits(k.angle))}), // ${k.angle}`);
  out.push('];', '', '/// Descriptors returned by cv.ORB::compute(), one row per keypoint.', '#[rustfmt::skip]',
    `pub(crate) const ORB_REF_DESCRIPTORS: [[u8; 32]; ${desc.rows}] = [`);
  for (let i = 0; i < desc.rows; i++) {
    out.push('    [' + Array.from(desc.data.subarray(i * 32, i * 32 + 32), hex8).join(', ') + '],');
  }
  out.push('];', '');
  fs.writeFileSync(OUT_RS, out.join('\n'));
  console.log(`wrote ${OUT_RS} (OpenCV ${version}, ${kps.length} keypoints, image fnv ${hex32(fnv1a32(px))})`);
  [img, kpv, orb, desc].forEach((m) => m.delete());
})().catch((e) => { console.error(e.message || e); process.exit(1); });
