# build-dual.ps1
# Automates building both Standard and SIMD versions of the WASM module.

$ErrorActionPreference = "Stop"

# Get the directory where the script is located
$scriptDir = $PSScriptRoot
$wasmDir = Join-Path $scriptDir ".." | Resolve-Path
$root = Join-Path $wasmDir "../.." | Resolve-Path
$pkgDir = Join-Path $wasmDir "pkg"

Write-Host "Cleaning up pkg directory..."
if (Test-Path $pkgDir) { Remove-Item -Recurse -Force $pkgDir }
New-Item -ItemType Directory -Path $pkgDir | Out-Null

# 1. Build Standard Version
# Copy LICENSE to wasm crate root so wasm-pack finds it
Copy-Item (Join-Path $root "LICENSE") -Destination $wasmDir

Write-Host "Building Standard Version..."
Set-Location $wasmDir
wasm-pack build --target web --out-dir pkg/dist-std --scope webarkit

# 2. Build SIMD Version
Write-Host "Building SIMD Version..."
$env:RUSTFLAGS = "-C target-feature=+simd128"
wasm-pack build --target web --out-dir pkg/dist-simd --scope webarkit -- --features simd
$env:RUSTFLAGS = ""

# Remove .gitignore files generated by wasm-pack (they contain '*' which blocks npm publish)
Remove-Item -Force (Join-Path $pkgDir "dist-std/.gitignore") -ErrorAction SilentlyContinue
Remove-Item -Force (Join-Path $pkgDir "dist-simd/.gitignore") -ErrorAction SilentlyContinue

# 3. Create Unified Package Infrastructure
Write-Host "Generating unified package.json..."

$stdPkgJsonPath = Join-Path $pkgDir "dist-std/package.json"
$pkgJson = Get-Content $stdPkgJsonPath -Raw | ConvertFrom-Json

# Add exports for standard and simd
$exports = [PSCustomObject]@{
    "." = "./dist-std/purecv_wasm.js"
    "./simd" = "./dist-simd/purecv_wasm.js"
}

# Remove files array so npm includes all files (dist-std and dist-simd)
$pkgJson.PSObject.Properties.Remove('files')

if (-not $pkgJson.PSObject.Properties['exports']) {
    $pkgJson | Add-Member -MemberType NoteProperty -Name "exports" -Value $exports
} else {
    $pkgJson.exports = $exports
}

# Ensure the name is scoped
$pkgJson.name = "@webarkit/purecv-wasm"

$finalPkgJsonPath = Join-Path $pkgDir "package.json"
$pkgJson | ConvertTo-Json -Depth 10 | Set-Content $finalPkgJsonPath

# Copy Readme to pkg root
$readmePath = Join-Path $wasmDir "README.md"
if (-not (Test-Path $readmePath)) {
    $readmePath = Join-Path $root "README.md"
}
if (Test-Path $readmePath) {
    Copy-Item $readmePath $pkgDir
}

Copy-Item (Join-Path $root "LICENSE") -Destination $pkgDir

Write-Host "Dual build complete! Package ready in crates/wasm/pkg"
Set-Location $root
