name: Rust CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-code-format:
    name: Check Code Format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Check formatting
      run: cargo fmt --all -- --check

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Build
      run: cargo build --verbose

    - name: Run tests (with parallel feature)
      run: cargo test --verbose --features parallel

    - name: Run tests (with simd feature)
      run: cargo test --verbose --features simd

    - name: Run tests (with ndarray feature)
      run: cargo test --verbose --features ndarray

    - name: Lint with clippy
      run: cargo clippy -- -D warnings
